#!/bin/bash

set -xeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
cd $SCRIPT_DIR
${SCRIPT_DIR}/.venv/bin/python "${SCRIPT_DIR}/app.py" --headless --device mps --ebook "$1" --voice "${2:-$SCRIPT_DIR/voices/eng/adult/male/MorganFreeman_24000.wav}"
